### ISSUE TITLE
Unable to parse private key

### ISSUE THREAD

**Issue by amenon** [GarettRogers/appengine-apns-gcm#3]
Thanks for creating this project. I am developing an APN module to work on AppEngine and am using similar code to your apn.py. However, I run into an issue when the socket tries to connect:
SSLError: _ssl module: Unable to parse private key.

My private key is a string that contains -----BEGIN RSA PRIVATE KEY----- to -----END RSA PRIVATE KEY----- and I pass the StingIO.StringIO of this string as the keyfile.

Am I missing anything?

**Comment by odednoam** [comment]
To my horror, adding "\n" at the end of the file (after END PRIVATE KEY) fixed it for me
